### ISSUE TITLE
Chapter04 missing file 

### ISSUE THREAD

**Issue by zmoe84** [PacktWorkshops/The-PHP-Workshop#4]
File function-average.php

**Comment by PacktSupport** [comment]
Hello zmoe84, thank you for raising this issue. We will get in touch with our development team and upload the missing example file  (function-average.php) as soon as possible. Thanks!

**Comment by PacktSupport** [comment]
Hello zmoe84, thank you for your patience! We have now uploaded the missing example file [here](https://github.com/PacktWorkshops/The-PHP-Workshop/blob/master/Chapter04/Examples/function-average.php). Let us know in case of any further issues. Thanks!
